### ISSUE TITLE
Allow async code

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/exit-hook#1]
Currently, only sync code can be executed.

Could use the `beforeExit` event.

**Comment by kevva** [comment]
Don't know if `beforeExit` is that useful since it's not emitted on `process.exit()` or other events that causes *explicit termination*.

**Comment by sindresorhus** [comment]
@kevva See https://github.com/sindresorhus/exit-hook/pull/4. Could use some help reviewing that.

**Comment by sindresorhus** [comment]
Relevant Node.js discussion: https://github.com/nodejs/node/issues/29480

**Comment by devsnek** [comment]
This is slightly different from that issue actually. We purposely disallow async tasks to be queued while node is exiting, and it isn't a goal of ours to allow that, since you could just delay the process exiting indefinitely...

**Comment by Townsheriff** [comment]
> This is slightly different from that issue actually. We purposely disallow async tasks to be queued while node is exiting, and it isn't a goal of ours to allow that, since you could just delay the process exiting indefinitely...

It wont stop users from stopping process anyway, if they want to dismiss some signals they can do it.  

It is very useful for cleaning spawned and detached resources.

**Comment by sindresorhus** [comment]
> We purposely disallow async tasks to be queued while node is exiting, and it isn't a goal of ours to allow that, since you could just delay the process exiting indefinitely...

I could delay it indefinitely synchronously already. I don't see why that should stop a highly desired feature. If delaying it indefinitely is a problem, add a reasonable timeout that can be configured.
