### ISSUE TITLE
Cannot use require on the module

### ISSUE THREAD

**Issue by EdmondScorp** [sindresorhus/exit-hook#18]
I get the following error:
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\user\Desktop\folder\node_modules\exit-hook\index.js from C:\Users\user\Desktop\folder
Instead change the require of index.js in C:\Users\user\Desktop\folder\main.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\Users\user\Desktop\folder\main.js:5:18) {
  code: 'ERR_REQUIRE_ESM'
}

I downgradedd to version 2.2.1 and it worked. What's the issue with the latest? I am using Node version 16.9.0

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
