### ISSUE TITLE
v3.1.0: exit-hook causes scripts to exit with error code 128 instead of 0

### ISSUE THREAD

**Issue by nolanlawson** [sindresorhus/exit-hook#23]
Hi, thanks for creating `exit-hook`! It is extremely useful. :slightly_smiling_face: 

I'm reporting an apparent regression in v3.1.0. [Here is a minimal repro](https://gist.github.com/nolanlawson/201fd03a6f44827153b8ded608ff5f5b).

To reproduce, run:

```sh
git clone https://gist.github.com/201fd03a6f44827153b8ded608ff5f5b.git repro
cd repro
npm i
node index.js
echo $?
```

With `exit-hook` v3.1.0, this will print `128` (the error code). Whereas if you do:

```
npm i --save exit-hook@3.0.0
node index.js
echo $?
```

Then it will print `0` (the successful exit code).

The `index.js` file itself is quite minimal:

```js
#!/usr/bin/env node

import exitHook from 'exit-hook'

exitHook(() => {
})
```

Here is the relevant environment info:

```
$ node --version
v16.18.0
$ npm --version
8.19.2
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
```

Thanks in advance for taking a look!

**Comment by sindresorhus** [comment]
// @jakobo

**Comment by jakobo** [comment]
The issue seems to be that `beforeExit` needs to behave identical to our PM2 handler. I've been able to create a fixture that replicates and will get a PR up shortly.
