### ISSUE TITLE
Should `minimumWait` be `maximumWait` ?

### ISSUE THREAD

**Issue by iwestlin** [sindresorhus/exit-hook#32]
https://github.com/sindresorhus/exit-hook/blob/34078d9abbc3ae74a7a5a30fb1009e974e71c46f/index.js#L46

Node will exit at (or before) `forceAfter` ms, so I think it should called `maximumWait`.

**Comment by sindresorhus** [comment]
// @jakobo

**Comment by jakobo** [comment]
> https://github.com/sindresorhus/exit-hook/blob/34078d9abbc3ae74a7a5a30fb1009e974e71c46f/index.js#L46
> 
> 
> 
> Node will exit at (or before) `forceAfter` ms, so I think it should called `maximumWait`.

Consider the following:

* `hookA` registers asynchronously with a 100ms wait time 
* `hookB` registers asynchronously with a 300ms wait time

At registration, this is the minimum time the hook will be waiting for. In the original PR we went back and forth on the name. I agree it feels confusing (even still).

I see two solutions, one of which would bump the major version

1. (4.0) Rename to `maximumWait` or better, just `wait`, further clarify the docs about how waiting works
2. (3.x) Rename to `maximumWait`, alias `minimumWait` and mark as deprecated

I'm leaning towards the first option. In 2 weeks, node lts rotates. I'd prefer to bundle this change with the end of node16 support & encourage people to stay on top of supported node versions.

**Comment by jakobo** [comment]
@iwestlin Draft PR is at https://github.com/sindresorhus/exit-hook/pull/33 if you'd like to take a look; it specifically addresses option 1, moving the minimum required node version to 18 and renaming to `wait` + adds docs for clarity. I'll move it out of draft tomorrow. I prefer to sit on a change like this for a day so I can reread the diff with fresh eyes and minimize PR review time for Sindre.

**Comment by iwestlin** [comment]
> At registration, this is the minimum time the hook will be waiting for.

Hi, I'm not sure what does *minimum* mean, even if there is only one registered hook with `forceAfter` waiting time, shouldn't it still be the maximum time node will be wating for?

```js
        // Force exit if we exceeded our wait value
	const asyncTimer = setTimeout(() => {
		done(true);
	}, forceAfter);

	await Promise.all(promises);
	clearTimeout(asyncTimer);
	done();
```

- If the task in `promises` finished before `forceAfter` ms, the `done()` will be called and Node exits;
- If the task in `promises` takes longer than `forceAfter` ms, `done(true)` in `setTimeout` will be called at `forceAfter` ms and Node exits, leaving task unfinished.

All in all, the *maximum* waiting time will be `forceAfter` ms. Did I miss something? Could you elaborate on where did the `minimum` come from?
